---
- name: Set hostname to {{ hostname }}
  hostname:
    name: "{{ hostname }}"

- name: Install required software packages
  apt:
    name: ['aptitude', 'git']
    state: present

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day

- include: docker.yml